theme: minima
title: My Research Blog in Mental Health Data Science
author: Aiying Zhang
email: zhangaiying0512@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an Assistant Professor in the School of Data Science at University of Virginia. 
  
  I use this blog to share useful stuff I've learned for mental health data science.  
  

# social links
twitter_username: aiying_zhang # DO NOT include the @ character, or else the build will fail!
github_username:  Aiying0512 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


